name: Run Tests - PyTorch 1.13
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *

jobs:
  run-pytorch-1_13:
    uses: ./.github/workflows/run_pytorch_tests.yml
    with:
      torch-version: "1.13.*"
