name: Run Keras Tests

on:
  workflow_call:
    inputs:
      tf-version:
        required: true
        type: string

jobs:
  run-tensorflow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.*
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
          pip install tensorflow==${{ inputs.tf-version }}
      - name: Run unittests
        run: |
          python -m unittest discover tests/keras_tests -v
